routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('seed', function () {
    Artisan::call('db:seed');
});

// Website
Route::middleware('count.visitor')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/about', [HomeController::class, 'about'])->name('about');
    Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
    Route::post('/contact', [HomeController::class, 'contactStore'])->name('contact-store');
    Route::get('/search', [PostController::class, 'search'])->name('search');
    Route::get('/highlight', [PostController::class, 'highland'])->name('highland');
    Route::get('/category/{slug}', [PostController::class, 'category'])->name('category');
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', [PostController::class, 'article'])->name('index');
        Route::get('/popular', [PostController::class, 'ArticlePopular'])->name('popular');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::prefix('news')->name('news.')->group(function () {
        Route::get('/', [PostController::class, 'news'])->name('index');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::post('/comment', [PostController::class, 'comment'])->name('comment');
    Route::get('/comment/{id}', [PostController::class, 'commentPost'])->name('comment-post');
    Route::prefix('auth')->name('auth.')->group(function () {
        Route::post('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/verification', [AuthController::class, 'verification'])->name('verification');
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    });
});





// Admin
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [Admin\AuthController::class, 'login'])->name('login');
    Route::post('/login', [Admin\AuthController::class, 'loginPost'])->name('login.post');

    Route::group(['middleware' => 'admin'], function(){
        Route::get('/logout', [Admin\AuthController::class, 'logout'])->name('logout');
        Route::get('/dashboard', [Admin\DashboardController::class, 'index'])->name('dashboard');
        Route::get('/dashboard/visitor', [Admin\DashboardController::class, 'visitor'])->name('dashboard.visitor');

        Route::prefix('master')->name('master.')->group(function () {
            Route::prefix('category-post')->name('category-post.')->group(function () {
                Route::get('/', [Admin\Master\CategoryPostController::class, 'index'])->name('index');
                Route::get('/datatable', [Admin\Master\CategoryPostController::class, 'datatable'])->name('datatable');
                Route::post('/store', [Admin\Master\CategoryPostController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [Admin\Master\CategoryPostController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [Admin\Master\CategoryPostController::class, 'update'])->name('update');
                Route::get('/delete/{id}', [Admin\Master\CategoryPostController::class, 'delete'])->name('delete');
            });
        });

        Route::prefix('post')->name('post.')->group(function () {
            Route::get('/', [Admin\PostController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\PostController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\PostController::class, 'create'])->name('create');
            Route::post('/store', [Admin\PostController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\PostController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\PostController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\PostController::class, 'delete'])->name('delete');
            Route::prefix('comment')->name('comment.')->group(function () {
                Route::get('/{id}', [Admin\PostController::class, 'comment'])->name('index');
                Route::get('/{id}/datatable', [Admin\PostController::class, 'commentDatatable'])->name('datatable');
                Route::post('/{id}/store', [Admin\PostController::class, 'commentStore'])->name('store');
                Route::get('/{id}/edit/{comment}', [Admin\PostController::class, 'commentEdit'])->name('edit');
                Route::post('/{id}/update/{comment}', [Admin\PostController::class, 'commentUpdate'])->name('update');
            });
        });

        Route::prefix('comment')->name('comment.')->group(function () {
            Route::get('/', [Admin\CommentController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\CommentController::class, 'datatable'])->name('datatable');
            Route::get('/show/{id}', [Admin\CommentController::class, 'show'])->name('show');
            Route::get('/hide/{id}', [Admin\CommentController::class, 'hide'])->name('hide');
            Route::get('/delete/{id}', [Admin\CommentController::class, 'delete'])->name('delete');
        });

        Route::prefix('ads')->name('ads.')->group(function(){
            Route::get('/', [Admin\AdsController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\AdsController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\AdsController::class, 'create'])->name('create');
            Route::post('/store', [Admin\AdsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\AdsController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\AdsController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\AdsController::class, 'delete'])->name('delete');
        });

        Route::prefix('setup')->name('setup.')->group(function(){
            Route::get('/about-us', [Admin\SetupController::class, 'aboutUs'])->name('about-us');
            Route::post('/about-us', [Admin\SetupController::class, 'aboutUsUpdate'])->name('about-us-update');
            Route::get('/footer', [Admin\SetupController::class, 'footer'])->name('footer');
            Route::post('/footer', [Admin\SetupController::class, 'footerUpdate'])->name('footer-update');
        });
    });
});

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="icon" type="image/png" href="{{ asset('favicon.ico') }}">
    <title>@yield('title') - {{ env('APP_NAME') }}</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="{{ asset('assets/backend/modules/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/modules/fontawesome/css/all.min.css') }}">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('assets/backend/modules/datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/modules/bootstrap-daterangepicker/daterangepicker.css') }}">
    @yield('library-style')

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/css/components.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/css/custom.css') }}">
    @yield('custom-style')
</head>

<body>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>
            @include('layouts.backend.navbar')
            @include('layouts.backend.sidebar')

            <!-- Main Content -->
            <div class="main-content">
                @yield('content')
            </div>
            
            @include('layouts.backend.footer')

        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="{{ asset('assets/backend/modules/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/popper.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/tooltip.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/moment.min.js') }}"></script>
    <script src="{{ asset('assets/backend/js/stisla.js') }}"></script>

    <!-- JS Libraies -->
    <script src="{{ asset('assets/backend/modules/blockUI/jquery.blockUI.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ asset('assets/backend/modules/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    @yield('library-script')

    <!-- Template JS File -->
    <script src="{{ asset('assets/backend/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/backend/js/custom.js') }}"></script>
    @yield('custom-script')
</body>

</html>

resources/views/layouts/backend/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">Copyright &copy; 2021 <div class="bullet"></div><a href="https://infoberitabali.com">Info Berita Bali</a></div>
    <div class="footer-right"></div>
</footer>

resources/views/layouts/backend/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <div class="mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </div>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/backend/img/avatar.png') }}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{ auth()->user()->name }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item has-icon">
                    <i class="fas fa-user"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('admin.logout') }}" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/backend/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('admin.dashboard') }}">Info Berita Bali</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('admin.dashboard') }}">IBB</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Main Menu</li>
            <li><a class="nav-link" href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-database"></i><span>Data Master</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.master.category-post.index') }}">Kategori Post</a></li>
                </ul>
            </li>
            <li><a class="nav-link" href="{{ route('admin.post.index') }}"><i class="fas fa-newspaper"></i> <span>Post</span></a></li>
            <li><a class="nav-link" href="{{ route('admin.comment.index') }}"><i class="fas fa-comments"></i> <span>Komentar</span></a></li>
            <li><a class="nav-link" href="{{ route('admin.ads.index') }}"><i class="fab fa-buysellads"></i> <span>Iklan</span></a></li>
            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-cogs"></i><span>Pengaturan</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.setup.about-us') }}">Tentang Kami</a></li>
                    <li><a class="nav-link" href="{{ route('admin.setup.footer') }}">Footer</a></li>
                </ul>
            </li>
            <li><a class="nav-link" href="{{ route('admin.logout') }}"><i class="fas fa-power-off"></i> <span>Logout</span></a></li>
        </ul>
    </aside>
</div>