routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('seed', function () {
    Artisan::call('db:seed');
});

// Website
Route::middleware('count.visitor')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/about', [HomeController::class, 'about'])->name('about');
    Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
    Route::post('/contact', [HomeController::class, 'contactStore'])->name('contact-store');
    Route::get('/search', [PostController::class, 'search'])->name('search');
    Route::get('/highlight', [PostController::class, 'highland'])->name('highland');
    Route::get('/category/{slug}', [PostController::class, 'category'])->name('category');
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', [PostController::class, 'article'])->name('index');
        Route::get('/popular', [PostController::class, 'ArticlePopular'])->name('popular');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::prefix('news')->name('news.')->group(function () {
        Route::get('/', [PostController::class, 'news'])->name('index');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::post('/comment', [PostController::class, 'comment'])->name('comment');
    Route::get('/comment/{id}', [PostController::class, 'commentPost'])->name('comment-post');
    Route::prefix('auth')->name('auth.')->group(function () {
        Route::post('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/verification', [AuthController::class, 'verification'])->name('verification');
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    });
});





// Admin
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [Admin\AuthController::class, 'login'])->name('login');
    Route::post('/login', [Admin\AuthController::class, 'loginPost'])->name('login.post');

    Route::group(['middleware' => 'admin'], function(){
        Route::get('/logout', [Admin\AuthController::class, 'logout'])->name('logout');
        Route::get('/dashboard', [Admin\DashboardController::class, 'index'])->name('dashboard');
        Route::get('/dashboard/visitor', [Admin\DashboardController::class, 'visitor'])->name('dashboard.visitor');

        Route::prefix('master')->name('master.')->group(function () {
            Route::prefix('category-post')->name('category-post.')->group(function () {
                Route::get('/', [Admin\Master\CategoryPostController::class, 'index'])->name('index');
                Route::get('/datatable', [Admin\Master\CategoryPostController::class, 'datatable'])->name('datatable');
                Route::post('/store', [Admin\Master\CategoryPostController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [Admin\Master\CategoryPostController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [Admin\Master\CategoryPostController::class, 'update'])->name('update');
                Route::get('/delete/{id}', [Admin\Master\CategoryPostController::class, 'delete'])->name('delete');
            });
        });

        Route::prefix('post')->name('post.')->group(function () {
            Route::get('/', [Admin\PostController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\PostController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\PostController::class, 'create'])->name('create');
            Route::post('/store', [Admin\PostController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\PostController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\PostController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\PostController::class, 'delete'])->name('delete');
            Route::prefix('comment')->name('comment.')->group(function () {
                Route::get('/{id}', [Admin\PostController::class, 'comment'])->name('index');
                Route::get('/{id}/datatable', [Admin\PostController::class, 'commentDatatable'])->name('datatable');
                Route::post('/{id}/store', [Admin\PostController::class, 'commentStore'])->name('store');
                Route::get('/{id}/edit/{comment}', [Admin\PostController::class, 'commentEdit'])->name('edit');
                Route::post('/{id}/update/{comment}', [Admin\PostController::class, 'commentUpdate'])->name('update');
            });
        });

        Route::prefix('comment')->name('comment.')->group(function () {
            Route::get('/', [Admin\CommentController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\CommentController::class, 'datatable'])->name('datatable');
            Route::get('/show/{id}', [Admin\CommentController::class, 'show'])->name('show');
            Route::get('/hide/{id}', [Admin\CommentController::class, 'hide'])->name('hide');
            Route::get('/delete/{id}', [Admin\CommentController::class, 'delete'])->name('delete');
        });

        Route::prefix('ads')->name('ads.')->group(function(){
            Route::get('/', [Admin\AdsController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\AdsController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\AdsController::class, 'create'])->name('create');
            Route::post('/store', [Admin\AdsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\AdsController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\AdsController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\AdsController::class, 'delete'])->name('delete');
        });

        Route::prefix('setup')->name('setup.')->group(function(){
            Route::get('/about-us', [Admin\SetupController::class, 'aboutUs'])->name('about-us');
            Route::post('/about-us', [Admin\SetupController::class, 'aboutUsUpdate'])->name('about-us-update');
            Route::get('/footer', [Admin\SetupController::class, 'footer'])->name('footer');
            Route::post('/footer', [Admin\SetupController::class, 'footerUpdate'])->name('footer-update');
        });
    });
});

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\Post\CommentService;
use App\Traits\Response;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CommentController extends Controller
{
    use Response;

    protected $commentService;

    public function __construct(
        CommentService $commentService
    )
    {
        $this->commentService = $commentService;
    }
    
    /**
     * Display data post.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.comment.index');
    }

    /**
     * list data post
     *
     * @return \Yajra\DataTables\Facades\DataTables
     */
    public function datatable()
    {
        $result = $this->commentService->listAllCommentLatest()->getResult();
        
        return DataTables::of($result)
                        ->addIndexColumn()
                        ->editColumn('title',function($data){
                            return $data->post->title;
                        })
                        ->editColumn('comment',function($data){
                            return $data->comment;
                        })
                        ->editColumn('created_at',function($data){
                            return $data->created_at->format('d-m-Y H:i:s');
                        })
                        ->editColumn('user',function($data){
                            return $data->user->name;
                        })
                        ->editColumn('active',function($data){
                            return $data->active;
                        })
                        ->addColumn('action',function($data){
                            $action = '<div class="dropdown d-inline">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-cog"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item has-icon" href="'. route($data->post->type_post . '.slug',['slug' => $data->post->slug]) .'"><i class="fas fa-eye"></i> Post Comment</a>';
                                            if ($data->active == 1) {
                                                $action .= '<a class="dropdown-item has-icon hide-comment" href="javascript:void(0)" data-id="'.$data->id.'"><i class="fas fa-pencil-alt"></i> Sembunyikan</a>';
                                            }else{
                                                $action .= '<a class="dropdown-item has-icon show-comment" href="javascript:void(0)" data-id="'.$data->id.'"><i class="fas fa-pencil-alt"></i> Tampilkan</a>';
                                            }
                                            $action .= '<a class="dropdown-item has-icon delete-comment" href="javascript:void(0)" data-id="'.$data->id.'"><i class="fas fa-trash-alt"></i> Delete</a>
                                        </div>
                                    </div>';
                            return $action;
                        })
                        ->rawColumns(['action'])
                        ->make(true);
    }

    /**
     * Show comment post.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        $result = $this->commentService->showComment($id);

        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }

    /**
     * Hide comment post.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function hide($id)
    {
        $result = $this->commentService->hideComment($id);

        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }

    /**
     * Delete comment post.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function delete($id)
    {
        $result = $this->commentService->deleteComment($id);

        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }
}

resources/views/admin/comment/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Komentar')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Komentar</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
            <div class="breadcrumb-item">Komentar</div>
        </div>
    </div>
    <div class="section-body">
        <div class="row mt-4">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Data Semua Komentar</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="table" width="100%">
                                <thead>                                 
                                    <tr>
                                        <th>No</th>
                                        <th>Komentar</th>
                                        <th>Judul Post</th>
                                        <th>Waktu</th>
                                        <th>Pengguna</th>
                                        <th>Status</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script src="{{ asset('assets/backend/js/comment.js') }}"></script>
<script>
    $(document).ready(function(){
        //  load table
        const url = "{{ route('admin.comment.datatable') }}";
        new table(url);
    });

    // show
    $('#table').on('click','.show-comment', function(){
        let id = $(this).data('id');
        let url = '{{ route("admin.comment.show",":id") }}';
            url = url.replace(':id',id); 
        new show(url);
    });

    // hide
    $('#table').on('click','.hide-comment', function(){
        let id = $(this).data('id');
        let url = '{{ route("admin.comment.hide",":id") }}';
            url = url.replace(':id',id); 
        new hide(url);
    });

    // delete
    $('#table').on('click','.delete-comment', function(){
        swal({
            title: 'Apakah anda yakin?',
            text: 'Data akan dihapus, tidak bisa dikembalikan lagi!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                let id = $(this).data('id');
                let url = '{{ route("admin.comment.delete",":id") }}';
                    url = url.replace(':id',id); 
                new destroy(url);
            }
        });
    });
</script>
@endsection