routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('seed', function () {
    Artisan::call('db:seed');
});

// Website
Route::middleware('count.visitor')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/about', [HomeController::class, 'about'])->name('about');
    Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
    Route::post('/contact', [HomeController::class, 'contactStore'])->name('contact-store');
    Route::get('/search', [PostController::class, 'search'])->name('search');
    Route::get('/highlight', [PostController::class, 'highland'])->name('highland');
    Route::get('/category/{slug}', [PostController::class, 'category'])->name('category');
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', [PostController::class, 'article'])->name('index');
        Route::get('/popular', [PostController::class, 'ArticlePopular'])->name('popular');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::prefix('news')->name('news.')->group(function () {
        Route::get('/', [PostController::class, 'news'])->name('index');
        Route::get('/{slug}', [PostController::class, 'slug'])->name('slug');
    });
    Route::post('/comment', [PostController::class, 'comment'])->name('comment');
    Route::get('/comment/{id}', [PostController::class, 'commentPost'])->name('comment-post');
    Route::prefix('auth')->name('auth.')->group(function () {
        Route::post('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/verification', [AuthController::class, 'verification'])->name('verification');
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    });
});





// Admin
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [Admin\AuthController::class, 'login'])->name('login');
    Route::post('/login', [Admin\AuthController::class, 'loginPost'])->name('login.post');

    Route::group(['middleware' => 'admin'], function(){
        Route::get('/logout', [Admin\AuthController::class, 'logout'])->name('logout');
        Route::get('/dashboard', [Admin\DashboardController::class, 'index'])->name('dashboard');
        Route::get('/dashboard/visitor', [Admin\DashboardController::class, 'visitor'])->name('dashboard.visitor');

        Route::prefix('master')->name('master.')->group(function () {
            Route::prefix('category-post')->name('category-post.')->group(function () {
                Route::get('/', [Admin\Master\CategoryPostController::class, 'index'])->name('index');
                Route::get('/datatable', [Admin\Master\CategoryPostController::class, 'datatable'])->name('datatable');
                Route::post('/store', [Admin\Master\CategoryPostController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [Admin\Master\CategoryPostController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [Admin\Master\CategoryPostController::class, 'update'])->name('update');
                Route::get('/delete/{id}', [Admin\Master\CategoryPostController::class, 'delete'])->name('delete');
            });
        });

        Route::prefix('post')->name('post.')->group(function () {
            Route::get('/', [Admin\PostController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\PostController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\PostController::class, 'create'])->name('create');
            Route::post('/store', [Admin\PostController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\PostController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\PostController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\PostController::class, 'delete'])->name('delete');
            Route::prefix('comment')->name('comment.')->group(function () {
                Route::get('/{id}', [Admin\PostController::class, 'comment'])->name('index');
                Route::get('/{id}/datatable', [Admin\PostController::class, 'commentDatatable'])->name('datatable');
                Route::post('/{id}/store', [Admin\PostController::class, 'commentStore'])->name('store');
                Route::get('/{id}/edit/{comment}', [Admin\PostController::class, 'commentEdit'])->name('edit');
                Route::post('/{id}/update/{comment}', [Admin\PostController::class, 'commentUpdate'])->name('update');
            });
        });

        Route::prefix('comment')->name('comment.')->group(function () {
            Route::get('/', [Admin\CommentController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\CommentController::class, 'datatable'])->name('datatable');
            Route::get('/show/{id}', [Admin\CommentController::class, 'show'])->name('show');
            Route::get('/hide/{id}', [Admin\CommentController::class, 'hide'])->name('hide');
            Route::get('/delete/{id}', [Admin\CommentController::class, 'delete'])->name('delete');
        });

        Route::prefix('ads')->name('ads.')->group(function(){
            Route::get('/', [Admin\AdsController::class, 'index'])->name('index');
            Route::get('/datatable', [Admin\AdsController::class, 'datatable'])->name('datatable');
            Route::get('/create', [Admin\AdsController::class, 'create'])->name('create');
            Route::post('/store', [Admin\AdsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [Admin\AdsController::class, 'edit'])->name('edit');
            Route::post('/update/{id}', [Admin\AdsController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [Admin\AdsController::class, 'delete'])->name('delete');
        });

        Route::prefix('setup')->name('setup.')->group(function(){
            Route::get('/about-us', [Admin\SetupController::class, 'aboutUs'])->name('about-us');
            Route::post('/about-us', [Admin\SetupController::class, 'aboutUsUpdate'])->name('about-us-update');
            Route::get('/footer', [Admin\SetupController::class, 'footer'])->name('footer');
            Route::post('/footer', [Admin\SetupController::class, 'footerUpdate'])->name('footer-update');
        });
    });
});

app/Models/CategoryPost.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class CategoryPost extends Model
{
    use HasSlug;
    
    protected $table = 'category_post';

    protected $fillable = [
        'name',
        'active'
    ];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
}

app/Http/Controllers/Admin/Master/CategoryPostController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Post\CategoryStoreResuest;
use App\Http\Requests\Admin\Post\CategoryUpdateResuest;
use App\Services\Post\CategoryService;
use App\Traits\Response;
use Yajra\DataTables\Facades\DataTables;

class CategoryPostController extends Controller
{
    use Response;
    
    protected $categoryService;
    
    public function __construct(
        CategoryService $categoryService
    )
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Page list data category post
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.master.category-post.index');
    }

    /**
     * list data category post
     *
     * @return \Yajra\DataTables\Facades\DataTables
     */
    public function datatable()
    {
        $result = $this->categoryService->listAll();

        return DataTables::of($result->getResult())
                        ->addIndexColumn()
                        ->editColumn('name',function($data){
                            return $data->name;
                        })
                        ->editColumn('active',function($data){
                            return ($data->active) ? "Aktif" : 'Tidak Aktif';
                        })
                        ->addColumn('action',function($data){
                            return '<div class="dropdown d-inline">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-cog"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item has-icon edit" href="javascript:void(0)" data-id="'.$data->id.'"><i class="fas fa-pencil-alt"></i> Edit</a>
                                            <a class="dropdown-item has-icon delete" href="javascript:void(0)" data-id="'.$data->id.'"><i class="fas fa-trash-alt"></i> Delete</a>
                                        </div>
                                    </div>';
                        })
                        ->rawColumns(['action'])
                        ->make(true);
    }

    /**
     * Create data category post
     *
     * @param \App\Http\Requests\Admin\Post\CategoryStoreResuest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(CategoryStoreResuest $request)
    {
        $result = $this->categoryService->store([
            'name' => $request->name,
            'active' => $request->active
        ]);
        
        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }
    
    /**
     * Get data category post
     *
     * @param integer $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit(int $id)
    {
        $result = $this->categoryService->findId($id);
        
        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }

    /**
     * Update data category post
     *
     * @param integer $id
     * @param \App\Http\Requests\Admin\Post\CategoryUpdateResuest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(CategoryUpdateResuest $request, int $id)
    {
        $result = $this->categoryService->update($id, [
            'name' => $request->name,
            'active' => $request->active
        ]);
        
        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }
        
    /**
     * Delete data category post
     *
     * @param integer $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function delete(int $id)
    {
        $result = $this->categoryService->delete($id);
        
        return $this->responseJson($result->isSuccess(), $result->getMessage(), $result->getResult(), $result->getCode());
    }
}

resources/views/admin/master/category-post/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Kategori Post')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Kategori Post</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="#">Data Master</a></div>
            <div class="breadcrumb-item">Kategori Post</div>
        </div>
    </div>

    <div class="section-body">
        <div class="card">
            <div class="card-header">
                <h5>Data Kategori Post</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12 pb-1">
                        <a href="javascript:void(0)" class="btn btn-primary btn-sm" id="add">Tambah Data</a>
                    </div>
                </div>
                <br>
                <div class="table-responsive">
                    <table class="table table-striped" id="table" width="100%">
                        <thead>                                 
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@include('admin.master.category-post.modal')
@endsection

@section('custom-script')
<script src="{{ asset('assets/backend/js/master/category-post.js') }}"></script>
<script>
    $(document).ready(function(){
        //  load table
        const url = "{{ route('admin.master.category-post.datatable') }}";
        new table(url);
    });

    // create
    $('#add').on('click', function(){
        $('.modal-title').text('Tambah Kategori');
        $('#form-modal').attr('action', "{{ route('admin.master.category-post.store') }}");
        $('#modal-form').modal('show');
    });
    
    // submit
    $('#form-modal').submit(function(e){
        e.preventDefault();
        const url = $(this).attr('action');
        const data = new FormData(this);
        new submit(url, data);
    });

    // edit
    $('#table').on('click','.edit', function(){
        let id = $(this).data('id');
        let url = '{{ route("admin.master.category-post.edit",":id") }}';
            url = url.replace(':id',id);

        let action = '{{ route("admin.master.category-post.update",":id") }}';
            action = action.replace(':id',id);
        $('#form-modal').attr('action', action);
        $('.modal-title').text('Edit Kategori');

        new edit(url);
    });

    // delete
    $('#table').on('click','.delete', function(){
        swal({
            title: 'Apakah anda yakin?',
            text: 'Data akan dihapus, tidak bisa dikembalikan lagi!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                let id = $(this).data('id');
                let url = '{{ route("admin.master.category-post.delete",":id") }}';
                    url = url.replace(':id',id); 
                new destroy(url);
            }
        });
    });
</script>
@endsection

resources/views/admin/master/category-post/modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="modal-form" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <form id="form-modal" onsubmit="return false;">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Nama Kategori">
                                </div>
                                <div class="error-name form-error text-danger fs-12"></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Status</label>
                                <div class="input-group">
                                    <select class="form-control" name="active" id="active">
                                        <option value="">- Pilih Status -</option>
                                        <option value="0">Tidak Aktif</option>
                                        <option value="1">Aktif</option>
                                    </select>
                                </div>
                                <div class="error-active form-error text-danger fs-12"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>